version: "3.9"
services:
  backend:
    build: ./backend
    container_name: bashful_bacon
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/backend
      - /backend/node_modules
  frontend:
    build: ./frontend
    container_name: feverous_ferret
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true
    tty: true